name: eventora
description: "Discover and book amazing events near you"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^7.0.2
  dotted_border: ^2.1.0
  cloud_firestore: ^6.1.2
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  firebase_storage: ^13.0.6
  image_picker: ^1.2.1
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.4
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  geolocator: ^11.0.0
  geocoding: ^2.1.1
  intl_phone_field: ^3.2.0
  flutter_launcher_icons: ^0.14.4
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  razorpay_flutter: ^1.4.0
  envied: ^0.5.4+1
  share_plus: ^10.1.3
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  envied_generator: ^0.5.4+1
  build_runner: ^2.4.13


flutter:
  uses-material-design: true
  assets:
    - assets/images/
 